name: Update README with Language Use Stats

on:
  schedule:
    - cron: "0 14 * * *" # Run every day at 2 PM

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Flask Application
        run: |
          export FLASK_APP=app.py
          flask run --host=0.0.0.0 --port=5000
